<?php

/**
 *
 *  * This is an iumio component [https://iumio.com]
 *  *
 *  * (c) Mickael Buliard <mickael.buliard@iumio.com>
 *  *
 *  * Bill&Go, gérer votre administratif efficacement [https://billandgo.fr]
 *  *
 *  * To get more information about licence, please check the licence file
 *
 */


namespace BillAndGoBundle\Repository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllEstimate($refuser)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select('a');
        $qb->where('a.refUser = :user')
            ->setParameter('user', $refuser)
            ->andWhere('a.type = 1');
        return $qb->getQuery()->getResult();
    }

    public function findAllBill($refuser)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select('a');
        $qb->where('a.refUser = :user')
            ->setParameter('user', $refuser)
            ->andWhere('a.type = 0');
        return $qb->getQuery()->getResult();
    }
}
