<?php

namespace BillAndGoBundle\Repository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllEstimate($refuser)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select('a');
        $qb->where('a.refUser = :user')
            ->setParameter('user', $refuser)
            ->andWhere('a.type = 1');
        return $qb->getQuery()->getResult();
    }

    public function findAllBill($refuser)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select('a');
        $qb->where('a.refUser = :user')
            ->setParameter('user', $refuser)
            ->andWhere('a.type = 0');
        return $qb->getQuery()->getResult();
    }
}
