<?php

namespace BillAndGoBundle\Repository;

/**
 * LegalTermsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegalTermsRepository extends \Doctrine\ORM\EntityRepository
{
}
