<?php

namespace BillAndGoBundle\Repository;

/**
 * LegalTermsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegalTermsRepository extends \Doctrine\ORM\EntityRepository
{
    public function lastLegal()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select('a.name, a.publicationDate, a.content');
        $qb->where('a.publicationDate IS NOT NULL')
            ->setMaxResults(1)
            ->orderBy("a.version",  "DESC")
            //->andWhere('a.type = 1')
        ;
        return $qb->getQuery()->getOneOrNullResult();
    }
}
