<?php

namespace BillAndGoBundle\Repository;

/**
 * NumerotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumerotationRepository extends \Doctrine\ORM\EntityRepository
{
}
