<?php

namespace MyJobManagerBundle\Repository;

/**
 * TaxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxRepository extends \Doctrine\ORM\EntityRepository
{
}
